In [ ]:
import numpy as np
import sklearn
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier


In [ ]:
# the 4 possible inputs for a logical operator
X_train = np.array([[1,1],[1,-1],[-1,1],[-1,-1]])
print(X_train)

# gold classes for AND, OR et XOR
Y_train_AND = [1,-1,-1,-1]
Y_train_OR = [1,1,1,-1]
Y_train_XOR = [-1,1,1,-1]

# TODO

# implement the forward propagation of a manually defined NN
# for a OR, a AND, and then a XOR (hence using a hidden layer)

# implement training and predication
# with Perceptron and MLPClassifier

# see fit and predict methods
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Perceptron.html
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Perceptron.html#sklearn.linear_model.Perceptron.fit

# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html



# TODO: for each of your classifiers, print the learnt parameters

[[ 1  1]
 [ 1 -1]
 [-1  1]
 [-1 -1]]


In [ ]:
# W(1) weight matrix at first hidden layer
W_1 = np.array([[1,1], [-1,-1]]).T
print(f"W_1:\n{W_1}\n")

# b(1) bias vector at first hidden layer
b_1 = np.array([1,1])
print(f"b_1: {b_1}\n")

print(f"X:\n {X_train}")

W_1:
[[ 1 -1]
 [ 1 -1]]

b_1: [1 1]

X:
 [[ 1  1]
 [ 1 -1]
 [-1  1]
 [-1 -1]]


In [ ]:
# getting z(1) pre-activations vector
Z_1 = np.dot(X_train, W_1) + b_1
print(f"Z_1:\n {Z_1}")



# defining activation function g_1 as hyperbolic tangent
g_1 = np.tanh



#applying activation func to Z(1)
A_1 = g_1(Z_1)

print(f"\nA_1:\n {A_1}")

Z_1:
 [[ 3 -1]
 [ 1  1]
 [ 1  1]
 [-1  3]]

A_1:
 [[ 0.99505475 -0.76159416]
 [ 0.76159416  0.76159416]
 [ 0.76159416  0.76159416]
 [-0.76159416  0.99505475]]


In [ ]:
# defining W(2) vector and b(2) bias for AND
W_2 = np.array([[1], [1]])
b_2 = np.array([-1])

# computing A(1).W(2) + b(2)
Z_2 = np.dot(A_1, W_2) + b_2

print(f"Z_2:\n{Z_2}")

#get sign for each input vector
O = np.sign(Z_2)
print(f"\nOutputs: \n{O}")

Z_2:
[[-0.7665394 ]
 [ 0.52318831]
 [ 0.52318831]
 [-0.7665394 ]]

Outputs: 
[[-1.]
 [ 1.]
 [ 1.]
 [-1.]]


In [ ]:
# training implementation of AND and OR operators using Perceptron class of sklearn package

# AND
perceptron = Perceptron()
perceptron.fit(X_train, Y_train_AND)

print(f"Weights for AND: {perceptron.coef_}")
print(f"Bias for AND: {perceptron.intercept_}")

print(f"Predictions: {perceptron.predict(X_train)}")
print(f"Score: {perceptron.score(X_train, Y_train_AND)}")

Weights for AND: [[1. 1.]]
Bias for AND: [-1.]
Predictions: [ 1 -1 -1 -1]
Score: 1.0


In [ ]:
# OR
perceptron = Perceptron()
perceptron.fit(X_train, Y_train_OR)

print(f"Weights for OR: {perceptron.coef_}")
print(f"Bias for OR: {perceptron.intercept_}")

print(f"Predictions: {perceptron.predict(X_train)}")
print(f"Score: {perceptron.score(X_train, Y_train_OR)}")

Weights for OR: [[1. 1.]]
Bias for OR: [1.]
Predictions: [ 1  1  1 -1]
Score: 1.0


In [ ]:
# TODO: for MLPClassifier: test with 1 hidden layer with 2 neurons, then with 100 neurons

# MLP with one hidden layer of 2 neurons
mlp = MLPClassifier(solver='lbfgs', activation='logistic', hidden_layer_sizes=(2,))
mlp.fit(X_train, Y_train_XOR)

print(f"W(1):\n{mlp.coefs_[0]}")
print(f"\nw(2):\n{mlp.coefs_[1]}")

print(f"\nb(1): {mlp.intercepts_[0]}")
print(f"\nb(2): {mlp.intercepts_[1]}")

print(f"Score: {mlp.score(X_train, Y_train_XOR)}")

W(1):
[[ 5.99530257  6.05771474]
 [-3.11903489  3.21859834]]

w(2):
[[-7.76317891]
 [ 7.73493482]]

b(1): [6.58391386 6.69276514]

b(2): [0.02782573]
Score: 0.5


In [ ]:
# MLP with one hidden layer of 100 neurons
mlp = MLPClassifier(solver='lbfgs', activation='logistic', hidden_layer_sizes=(100,))
mlp.fit(X_train, Y_train_XOR)

print(f"W(1):\n{mlp.coefs_[0]}")
print(f"\nw(2):\n{mlp.coefs_[1]}")

print(f"\nb(1): {mlp.intercepts_[0]}")
print(f"\nb(2): {mlp.intercepts_[1]}")

print(f"Score: {mlp.score(X_train, Y_train_XOR)}")

W(1):
[[-2.64062568e-01  4.66747795e-01  8.56203888e-01 -8.50324514e-01
  -2.61352009e+00  1.50815398e-01 -1.15058873e+00 -7.54556616e-01
  -3.44339973e-01  1.34329155e-01  1.38000580e+00 -2.24915768e-01
   2.26282859e-01 -5.81440611e-01 -1.67524792e-01  1.08509297e+00
   4.58868797e-01  1.73018932e+00  6.37557094e-01  5.21436151e-01
  -1.61143424e-01 -2.52272311e-01 -3.69867110e-01  2.07410453e-01
  -3.56138398e-01 -3.28723291e-01  1.14178005e+00  2.22418042e-01
  -2.30358983e-01  4.29528906e-02 -2.81897343e+00 -8.77933237e-02
  -6.87805619e-01 -3.20173333e-02 -1.36560473e-01  2.38777175e-01
   4.42414721e-01  8.98704559e-01  4.18061568e-01 -3.14844401e-01
   1.97024981e-01  2.39500124e-03 -7.01442062e-01 -1.50857290e-01
   1.27957067e-01  2.09037938e+00  1.48958410e-01 -2.73421390e-01
   2.35964037e-02 -1.38218404e+00 -3.63775200e-01  3.74379245e-02
  -2.54075794e-01  1.59651498e-01  6.31245716e-01  1.28818761e-01
   1.18140848e+00 -6.12498090e-01  1.45478509e-01  4.37316156e-01
  -7

In [ ]:
# backpropagation example

import numpy as np

# define the sigmoid function
def sigmoid(x, derivative=False):

    if (derivative == True):
        return sigmoid(x,derivative=False) * (1 - sigmoid(x,derivative=False))
    else:
        return 1 / (1 + np.exp(-x))

# choose a random seed for reproducible results
np.random.seed(1)

# learning rate
alpha = .1

# number of nodes in the hidden layer
num_hidden = 3

# inputs
X = np.array([  
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 0],
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
])

# outputs
# x.T is the transpose of x, making this a column vector
y = np.array([[0, 1, 0, 1, 1, 0]]).T

# initialize weights randomly with mean 0 and range [-1, 1]
# the +1 in the 1st dimension of the weight matrices is for the bias weight
hidden_weights = 2*np.random.random((X.shape[1] + 1, num_hidden)) - 1
output_weights = 2*np.random.random((num_hidden + 1, y.shape[1])) - 1

# number of iterations of gradient descent
num_iterations = 10000

# for each iteration of gradient descent
for i in range(num_iterations):

    # forward phase
    # np.hstack((np.ones(...), X) adds a fixed input of 1 for the bias weight
    input_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), X))
    hidden_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), sigmoid(np.dot(input_layer_outputs, hidden_weights))))
    output_layer_outputs = np.dot(hidden_layer_outputs, output_weights)

    # backward phase
    # output layer error term
    output_error = output_layer_outputs - y
    # hidden layer error term
    # [:, 1:] removes the bias term from the backpropagation
    hidden_error = hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) * np.dot(output_error, output_weights.T[:, 1:])

    # partial derivatives
    hidden_pd = input_layer_outputs[:, :, np.newaxis] * hidden_error[: , np.newaxis, :]
    output_pd = hidden_layer_outputs[:, :, np.newaxis] * output_error[:, np.newaxis, :]

    # average for total gradients
    total_hidden_gradient = np.average(hidden_pd, axis=0)
    total_output_gradient = np.average(output_pd, axis=0)

    # update weights
    hidden_weights += - alpha * total_hidden_gradient
    output_weights += - alpha * total_output_gradient

# print the final outputs of the neural network on the inputs X
print("Output After Training: \n{}".format(output_layer_outputs))

Output After Training: 
[[2.11135662e-04]
 [9.99525588e-01]
 [1.66889680e-04]
 [9.99576185e-01]
 [9.99362960e-01]
 [1.30185107e-03]]
